### ISSUE TITLE
Missing Faculties

### ISSUE THREAD

**Issue by himkwtn** [thinc-org/open-reg-backend#61]
40 sar
56 basci

**Comment by himkwtn** [comment]
migrate existing data as well

**Comment by fivechjr** [comment]
**NOTE:**
40 - SCHOOL OF AGRICULTURAL RESOURCES
56 - BACHELOR OF ARTS AND SCIENCE IN INTEGRATED INNOVATION

**Comment by fivechjr** [comment]
Done.
